server:
  port: 8090

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          ppod:
            registrationId: ppod
            clientId: 630edf9c9ebf675e980c
            clientSecret: c43d9bf9520a94529f283eb1ea90c3ae87208fed
            scope: profile
            provider: ppod
        provider:
          ppod:
            user-info-uri: https://api.github.com/user

service:
  version: @project.version@
  api:
    version: 1.0

logging:
  level.ru.cbr.rpocr: DEBUG