server:
  port: 8089

spring:
  rsocket:
    server:
      mapping-path: /rsocket
      transport: websocket

rsocket:
  security:
    oauth2:
      introspection:
        opaque:
          introspection-uri: http://localhost:8090/introspect
          introspection-client-id: 630edf9c9ebf675e980c
          introspection-client-secret: c43d9bf9520a94529f283eb1ea90c3ae87208fed

service:
  version: @project.version@
  api:
    version: "1.0"

spark:
  sparkHome: "/home/andrei/spark-2.4.4-bin-hadoop2.7"
  javaHome: "/usr/lib/jvm/java-8-oracle"
  appResource: "/home/andrei/develop/java/rpocr/web/service/calc-rate-launcher/target/calc-rate-driver.jar"
  mainClass: "ru.cbr.rpocr.spark.crd.Main"
  master: "spark://172.17.0.4:7077"
  redirectOutputFileName: "spark-launcher.out.log"

logging:
  level:
    ru.cbr.rpocr: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.rsocket: DEBUG
    reactor.netty.http.server.AccessLog: INFO
#  level.org.springframework: DEBUG